### ISSUE TITLE
Feature requests: feedback to a user's contribution

### ISSUE THREAD

**Issue by Jobava** [translate/pootle#4030] opened 2015-09-04 05:05 UTC
1. Add small textboxes next to suggestions to give reasons why certain suggestions are rejected.

2. Notify the contributor that their suggestions were rejected or accepted (perhaps daily, weekly, selectable from the user's settings).

3. Give contributers a unified view of their contributions and why they were rejected, if there is a reason attached.

4. Create a list of "canned motives" for reviewers to use, locale-specific, admin-modifiable, which reviewers could select from a dropdown or some other UI metaphor to speed up review and encourage feedback.

**Comment by julen** [comment] 2015-09-04 08:15
Somehow dupe of #2596.

**Closed by julen** 2015-09-04 08:15 UTC
