### ISSUE TITLE
Pootle FS does not expire cache data on sync

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#5688] opened 2016-12-09 17:11 UTC
As an logged in admin user:

* Create empty Pootle FS project
* View project - all blank i.e no languages
* Do `pootle fs` magic and import project
* View project, and not languages are not present.  Log you can drill down and you will find them.

We're clearly caching the old data.  I guess the same applies to any individual store that is loaded.

**Comment by unho** [comment] 2017-01-04 15:08
Duplicate of #5757.

**Closed by unho** 2017-01-04 15:08 UTC
Labels: pootle_fs
