### ISSUE TITLE
Can't retry failed jobs and refresh_stats

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#4062] opened 2015-09-14 10:55 UTC
Since you closed my issue without considering my last reply (and that is bad, the beauty of reporting an issue is to fix that)... anyway i tried everything was on internet but i keep having this

```pytb
Traceback (most recent call last):
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 459, in refresh_stats
    super(Command, Command()).handle_noargs(**options)
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/__init__.py", line 97, in handle_noargs
    self.handle_all(**options)
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 130, in handle_all
    super(Command, self).handle_all(**options)
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/__init__.py", line 112, in handle_all
    for project in project_query.iterator():
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 701, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 787, in execute_sql
    cursor.execute(sql, params)
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    return self.cursor.execute(query, args)
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (2006, 'MySQL server has gone away')
2015-09-14T10:49:08 Moving job to u'failed' queue
2015-09-14T10:49:08
```

I have 12 failed jobs, i keep using "pootle retry_failed_jobs" but i increase the jobs failed.
According to the guides on internet I increased the ```max_allowed_packet=64M``` in ```my.conf``` and the ```wait_timeout=600``` too
IT DIDN'T WORK... so the final solution is pootle... please dont close the issue and try to fix/help

**Comment by phlax** [comment] 2015-09-14 11:12
hi @JohnnyKing94 i would like to help if i can.

Can you confirm if this is a new installation or an upgrade?

Also can you confirm if you are using 2.7.0?

**Comment by JohnnyKing94** [comment] 2015-09-14 11:19
Yes i said on another post... this is a new installation (both enviroment and pootle)... and this is the output of pootle

```pootle --version
Pootle 2.7.0 (Django 1.7.10, Translate Toolkit 1.13.0)```

**Comment by phlax** [comment] 2015-09-14 11:21
ref #4050

**Comment by JohnnyKing94** [comment] 2015-09-14 11:21
I successfully installed db and filled with all the data with
```
pootle migrate
pootle initdb
```

So it's not a DB problem here, but something related to the code...

**Comment by phlax** [comment] 2015-09-14 11:33
> So it's not a DB problem here, but something related to the code...

You may well be right - but i havent seen this issue so far in our installation environments - I definitely would like to establish the cause though.

Im just going to test and see if i can trigger the error and will keep you updated with any progress.

**Comment by unho** [comment] 2015-09-14 11:37
Which MySQL version is being used? Which Redis version? Also please provide the output of `pip freeze`.

**Comment by JohnnyKing94** [comment] 2015-09-14 11:53
This is the output of pip freeze of my env
```
click==5.1
cssmin==0.2.0
diff-match-patch==20121119
Django==1.7.10
django-allauth==0.23.0
django-assets==0.11
django-contact-form==1.0
django-overextends==0.4.0
django-redis==4.2.0
django-rq==0.8.0
elasticsearch==1.6.0
lxml==3.4.4
msgpack-python==0.4.6
MySQL-python==1.2.5
oauthlib==1.0.3
Pootle==2.7.0
python-Levenshtein==0.12.0
python-openid==2.2.5
redis==2.10.3
requests==2.7.0
requests-oauthlib==0.5.0
rq==0.5.5
six==1.9.0
sphinx-me==0.3
translate-toolkit==1.13.0
urllib3==1.12
webassets==0.11
wheel==0.24.0
```

This is redis-server
```
redis-server --version
Redis server v=3.0.4 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=e10d4bb04434c274
```

This is mysql
```
mysql --version
mysql  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (x86_64) using readline 6.2
```

**Comment by ta2-1** [comment] 2015-09-14 13:09
hi @JohnnyKing94 
> I successfully installed db and filled with all the data

did you mean you filled your db with a sample data?

how do you start rqworker? how many running instances do you have?

**Comment by phlax** [comment] 2015-09-14 13:52
hi @JohnnyKing94 

I was just testing out the 2.7.0 install and may have replicated the problem that you were having.

I believe that the issue may have been resolved in the 2.7.1 version which we are about to release (we are expecting tomorrow).

Would you be willing to test out installing from our git repo? I can provide more instructions on how if you that helps.

Otherwise if you could try installing again once 2.7.1 is released that would be great - and hopefully will resolve the problem that you have had.

**Comment by JohnnyKing94** [comment] 2015-09-14 14:14
Before of this new installation i tried to use the git version, but at the step of making the static assets with npm and Node.js i had several problems, so i removed the env and made a new one using the pip version with the statics already included
```
I meant this part
(env) $ cd pootle/static/js
(env) $ npm install
(env) $ cd ../../..
(env) $ make assets
```

I think i will wait tomorrow for the new pip version... and see if it has been resolved ;) 

What's changes in the pootle.conf from 2.7.0 to 2.7.1??? Will i have to edit something?

**Comment by unho** [comment] 2015-09-15 21:32
> What's changes in the pootle.conf from 2.7.0 to 2.7.1??? Will i have to edit something? and the DB??

Yes, we introduced transaction_hooks so you will have to edit the config. The changes to the DB are handled by the migrations.

**Comment by JohnnyKing94** [comment] 2015-09-15 21:55
Ok thank you... I'll be waiting for the new pip version... I hope it will be soon this week :+1:

**Comment by JohnnyKing94** [comment] 2015-09-19 15:03
Now you can close, i just updated to 2.7.1 and everything works now... i'm gonna report other issues, but this one can be tagged as closed.

Thank you to everyone ;) :+1:

**Closed** 2015-09-19 15:12 UTC
