### ISSUE TITLE
No way to download files via default installation

### ISSUE THREAD

**Issue by avesus** [translate/pootle#3734] opened 2015-05-14 12:23 UTC
TemplateSyntaxError: "cache" tag got an unknown variable: u'settings.CACHE_TIMEOUT'

Pootle 2.5.1.1
Translate Toolkit 1.13.0
Django 1.4.20

**Comment by avesus** [comment] 2015-05-14 12:29
https://github.com/translate/pootle/issues/3183

**Comment by benallard** [comment] 2015-07-21 14:56
Same one here, pip install on jessie, minimal config, running 2.5.1.3

**Comment by benallard** [comment] 2015-07-22 08:14
And no, setting ``ALLOWED_HOSTS`` didn't solved it.

**Comment by julen** [comment] 2015-07-22 08:25
@benallard @avesus how did you guys install Pootle? I cannot reproduce any of these by [following the installation instructions](http://docs.translatehouse.org/projects/pootle/en/stable-2.5.1/server/installation.html#installing-pootle).

**Comment by benallard** [comment] 2015-07-22 08:36
pip install in a virtualenv ... and then cherrypy + nginx

**Comment by benallard** [comment] 2015-07-22 08:44
You can find my config file here: http://sprunge.us/baGR Maybe I'm missing some mandatory values ?

**Comment by julen** [comment] 2015-07-22 08:46
> pip install in a virtualenv ... and then cherrypy + nginx

Is this all you did? You mention no `pootle setup` whatsoever.

**Comment by benallard** [comment] 2015-07-22 08:48
I did ran ``pootle setup``.

```
2015-07-21 05:46:42,716 INFO Loading custom settings from '/home/pootle/.pootle/pootle.conf'...
2015-07-21 03:46:42,820 INFO Using Python PO
2015-07-21 03:46:42,888 INFO Pootle is already up-to-date.
```

**Comment by julen** [comment] 2015-07-22 08:52
Can you try in a fresh virtualenv please? I'm afraid I cannot reproduce it :confused:

**Comment by benallard** [comment] 2015-07-22 09:11
I did the following:

- deleted the virtualenv
- created a new virtualenv
- installed pootle (pip install pootle==2.5.1.3)
- added python-Levenshtein to the virtualenv.
- copied my config file (see above) under ~/.pootle/pootle.conf
- ran pootle setup
- ran pootle run_cherrypy

First conmnection takes some time, login as admin, open Terminology -> Afrikaans (first one on the list), clicked download, got nothing (0 bytes), but no traceback !
Went to the administration interface, enabled download for 'nobody' (Why isn't that default ?), tried with wget, wget says download failed, 500 Internal Server error, traceback can be seen.

**Comment by benallard** [comment] 2015-07-22 13:33
I've made some progress there.

I believe the culprit is ``django.views.static.serve``. As when I add this to my nginx configuration, it's just working fine:

```
  location /export/ {
          alias /home/pootle/venv/lib/python2.7/site-packages/pootle/po/;
      }
```

When I bypass nginx (directly access my server via the port 8000), I have no way to download my files, they are always served as being empty. (or generate a 500 when downloaded from wget).

Solution => ship nginx with pootle ...

Now the weird part: download of xliff isn't done via the ``/export/`` path, so I should get them the same regardless on which port I try to download them. That's wrong, I get full files via the port 80 (via nginx), and I inly get empty files via the port 8000 ... Go figure.

**Comment by julen** [comment] 2015-07-22 16:25
Thanks for taking your time to look into this @benallard.

Serving the exportable files directory via the web server is the suggested approach (in fact, there's already [a comment in the source code](https://github.com/translate/pootle/blob/stable/2.5.1/pootle/urls.py#L36), and serving files in production via Django's method is [highly discouraged](https://docs.djangoproject.com/en/1.4/ref/contrib/staticfiles/#static-file-development-view)). I'm surprised I cannot find any references to it in the docs; any ideas @translate/house?

Since everyone is working towards the next version, and a whole lot of things have changed, I have filed #3913 to address the documentation part. Other than that, there's nothing else we can do here, so I'll proceed to close the issue (already adjusted the title).

--

*Ship nginx with Pootle....* :smile:
The thing is the default Pootle installation via pip is left as an easy way to test what Pootle looks like. It's just a playground, and [the warning is clear in the installation docs](http://docs.translatehouse.org/projects/pootle/en/stable-2.5.1/server/installation.html#initializing-the-configuration).

**Closed by julen** 2015-07-22 16:25 UTC
