### ISSUE TITLE
`English` is missed in Language dropdown

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4705] opened 2016-05-04 15:15 UTC
We allow to use English as template source language. But then `English` is not shown in language dropdown in nav bar.
![image](https://cloud.githubusercontent.com/assets/682845/15017459/5e2b75fc-121e-11e6-9b46-b2361cfd2156.png)

**Comment by julen** [comment] 2016-05-04 15:17
This is a dupe of #3192.

**Closed by julen** 2016-05-04 15:17 UTC
