### ISSUE TITLE
`update_stores` does not obsolete removed strings if they have suggestions

### ISSUE THREAD

**Issue by rimas-kudelis** [translate/pootle#6572] opened 2017-07-18 13:50 UTC
# Steps to reproduce:
- Add a suggestion to a string
- remove that string from the source file
- run `update_stores`

# Results (Expected/Actual):
**Expected:** the string should should have been obsolete along with all its suggestions (or suggestions could have been removed)
**Actual:** the string with the suggestion remains visible in Pootle.

# Environment (i.e. 'pootle --version', DB, OS, Browser):
```
(env)[pootle@localizer repo]$ pootle --version
Pootle 2.8.0rc6 (Django 1.10.7, Translate Toolkit 2.2.3)
```

**Comment by phlax** [comment] 2017-08-15 10:35
@rimas-kudelis i have tested this on rc6 and not been able to reproduce this, can you double check and see if there is something else other than adding a suggestion that might have been the cause

**Comment by phlax** [comment] 2017-09-06 07:55
closing as unable to repro, if problem occurs again please re-open

**Closed by phlax** 2017-09-06 07:55 UTC
