### ISSUE TITLE
Error when upgrading

### ISSUE THREAD

**Issue by ambroisemaupate** [translate/pootle#3428] opened 2014-12-18 14:12 UTC
```
(env)pootle@xxxxxx:~$ pip install git+https://github.com/translate/pootle.git@stable/2.6.0
…
(env)pootle@xxxxxx:~$ pootle setup
…
```

When I try to perform migrations I’ve got some blocking errors.

```pytb
(env)pootle@xxxxxx:~$ pootle migrate
2014-12-18 15:08:06,546 INFO Loading custom settings from '/home/pootle/.pootle/pootle.conf'...
2014-12-18 14:08:06,828 INFO Using Python PO
Running migrations for accounts:
 - Migrating forwards to 0003_auto__inherit_from_permissionsmixin.
 > pootle_translationproject:0002_auto__del_field_translationproject_description_html__chg_field_transla
FATAL ERROR - The following SQL query failed: ALTER TABLE "pootle_app_translationproject" DROP COLUMN "description_html" CASCADE;
The error was: ERREUR:  la colonne « description_html » de la relation « pootle_app_translationproject » n'existe pas

Error in migration: pootle_translationproject:0002_auto__del_field_translationproject_description_html__chg_field_transla
Traceback (most recent call last):
  File "/home/pootle/www/pootle/env/bin/pootle", line 9, in <module>
    load_entry_point('Pootle==2.6.0-rc2', 'console_scripts', 'pootle')()
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/pootle/runner.py", line 171, in main
    django_settings_module='pootle.settings')
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/pootle/runner.py", line 150, in run_app
    management.execute_from_command_line([runner_name] + remainder)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/south/migration/migrators.py", line 84, in run_migration
    migration_function()
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_translationproject/migrations/0002_auto__del_field_translationproject_description_html__chg_field_transla.py", line 12, in forwards
    db.delete_column('pootle_app_translationproject', 'description_html')
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/south/db/generic.py", line 54, in _column_rm
    return func(self, table, column, *args, **opts)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/south/db/generic.py", line 911, in delete_column
    self.execute(self.delete_column_string % params, [])
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/south/db/generic.py", line 282, in execute
    cursor.execute(sql, params)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: ERREUR:  la colonne « description_html » de la relation « pootle_app_translationproject » n'existe pas
```

And I can’t use Pootle anymore:

![capture d ecran 2014-12-18 a 15 11 20](https://cloud.githubusercontent.com/assets/380026/5489303/305cc8d4-86c8-11e4-9954-2233929e562e.png)

**Comment by dwaynebailey** [comment] 2015-01-06 09:37
@unho do we have anything in our docs or in the ``pootle upgrade`` that warns about this?  We should at least warn so that we don't get people into these situations while we don't have a ``2.7.0`` endpoint.

**Comment by unho** [comment] 2015-01-07 11:08
@dwaynebailey Do you mean about people not fresh installing 2.6.x? If yes, to be sure we should remove the package from PyPI, and alter the docs. We already have altered the setup management command in https://github.com/translate/pootle/commit/bdc73a1599.

**Comment by unho** [comment] 2015-01-07 21:03
Just for the record, the 2.6.x packages are no longer available on PyPI and GitHub, and the docs for stable/2.6.0 branch have been altered.

**Comment by jleclanche** [comment] 2015-01-16 10:31
Dupe of #2804

I looked at this and it makes no sense that the `description_html` column would be missing from a migration point of view, unless the migration has already been run (which should not happen). Commit ef6ba22f92c313f8ccfbbebbd556cc3bec8f1f1e is related. I guess the issue was an old instance upgraded to 2.6.0 before that commit, in which case this is fixed.

**Closed by jleclanche** 2015-01-16 10:31 UTC
Labels: core-migration
