### ISSUE TITLE
Remove the visible stats refresh timer

### ISSUE THREAD

**Issue by jleclanche** [translate/pootle#3938] opened 2015-07-31 14:50 UTC
When stats are being refreshed, there is a running timer that says "This page will refresh in x seconds".

The timer is distracting and unnecessary. As I said on IRC:

> @jleclanche a timer is a moving part, moving parts are a UI item to avoid
@jleclanche this is avoidable
@jleclanche moving parts should be avoided because they are distracting; this is especially distracting because it contrasts so massively with the rest of the page, giving the impression that the user direly needs to take action, even though this is completely passive

To be clear, this isn't about *removing* the timer, just its visibility to the user.

**Comment by dwaynebailey** [comment] 2015-07-31 14:59
+1 for this, it creates angst when none is needed.  Either in a situation when stats goes out of wack or whe refresh_stats is first active.  The message itself is clear enough without the countdown.

**Comment by iafan** [comment] 2015-07-31 17:10
I disagree. Removing the dynamic counter will give an impression that nothing happens, and people don't know how much to wait till the stats are updated (they will likely start reloading the page manually instead of just waiting). The banner is supposed to be distracting, because it indicates that the stats are invalid, and clicking on some links down the page may lead to unexpected results. However, under properly functioning translation server, stats calculation should take no more than 1-2 seconds, so this message shouldn't really bother end users in real life.

The same dynamic counter is displayed in e.g. Gmail when it experiences connection problems, for example:
![screenclip 5](https://cloud.githubusercontent.com/assets/1728158/9012765/3f3b9c18-376c-11e5-8f74-0d7283fd0215.png)

**Comment by unho** [comment] 2015-07-31 17:13
I agree with @iafan. If the problem is that it never goes away, the real cause must be addressed instead of hiding this valuable notice.

**Comment by jleclanche** [comment] 2015-07-31 17:18
@iafan The connection timer in gmail is a lot more important than stats diplay. I don't think this is a fair comparison. (And Google isn't really a UX model to follow lately)

**Comment by jleclanche** [comment] 2015-07-31 17:20
Personally btw I don't think a message is necessary at all given that we have other means of displaying that stats are out of date.

**Comment by iafan** [comment] 2015-07-31 17:24
We've been living with this banner for many months, and didn't hear any complaints from translators. On the contrary, such a banner helped us identify issues with stats calculation and overall server health, so I personally consider it very important. If you see that banner for a second or two, it shouldn't bother you — you will not typically notice any dynamic counter at all. If you see it for more than that, just go and fix the server.

**Comment by ta2-1** [comment] 2015-07-31 18:30
I agree with @iafan. I wouldn't be able to know about problems with stats if I we didn't have this banner. And I don't remember when I saw this banner and everything worked as expected.

**Comment by julen** [comment] 2015-08-01 09:16
I can understand the angst when the banner is displayed *permanently*, but that indicates that either you screwed something up on the server, or you are running `refresh_stats`, which is needed just once before exposing the server to users.

As I already mentioned on IRC, there's no improvement in not letting users know **when** the refresh will happen. It's terrible actually: the sense of abrupt surprise is added, since the reload will happen out of the blue for the user.

Having said that, consider me +1 to close this as invalid.

**Comment by jleclanche** [comment] 2015-08-01 13:01
If you guys are never seeing this timer, I don't see why the pushback needs to be so aggressive on this one. The same UX rules apply whether it's displayed permanently or once a forthnight. It just so happens that with a couple of servers being buggy, the issue is more prominent.

**Comment by iafan** [comment] 2015-08-01 18:07
We're almost never seeing this banner when server works as expected. But when there's a problem with the server, we want everybody to clearly see it (and report the problem to us). If one prefers not to fix the server and just skip seeing that banner, they can add a simple override CSS style that will hide that banner altogether, and rest in their ignorance. I don't know how to make this even more straightforward.

**Comment by jleclanche** [comment] 2015-08-01 21:28
Again, this is about removing the *timer*, not the banner. I think the banner is unnecessary but that's out of scope of this bug.

**Comment by iafan** [comment] 2015-08-01 21:41
I think both I and Julen provided a pretty good reasoning of why the visible countdown timer is better than the lack thereof. You consider this a bad UX, but we consider the counter rather a UX improvement that helps users understand what's going on, whether and when the refresh is going to happen, and whether it is the server side issue with the stats, or their page just got in a bad state and needs to be reloaded manually.

**Comment by unho** [comment] 2015-08-18 08:55
I am closing this because IMHO good reasons were provided to reject the request.

**Closed by unho** 2015-08-18 08:55 UTC
Labels: ui
