### ISSUE TITLE
When uploading translation files, async worker is triggered before transaction completes (was: cache is invalidated before changes are applied)

### ISSUE THREAD

**Issue by phlax** [translate/pootle#3974] opened 2015-08-14 09:08 UTC
To reproduce:

- download translation file
- make change (change 1)
- upload file

At this point the stats/last activity does not show change 1

- download translation file again
- make change (change 2)
- upload file

At this point the stats/last activity shows change 1 and not change 2

**Comment by phlax** [comment] 2015-08-16 13:10
Ive tracked down the problem with this. The transaction in which the updates happen have not completed by the time the async worker is triggered - the stats are therefore calculated against the previous state of the db.

There are some really ugly hacks that would make this work, but the proper solution is to only trigger the async worker once the transaction has completed.

This is possible in django 1.9 (https://docs.djangoproject.com/en/dev/releases/1.9/), or perhaps by using django-transaction-hooks (https://pypi.python.org/pypi/django-transaction-hooks)

**Comment by ta2-1** [comment] 2015-08-16 20:32
is it ok to upload a big file in one transaction? what behavior will we get with conflictive editing from web UI?

**Comment by phlax** [comment] 2015-08-16 21:48
I don't think these things are affected by this PR.

This commit waits before triggering the async code until the transaction has been committed - basically at the end of the request.

Im not sure that ive necessarily put the on_commit hook in the right place, but im sure its necessary

**Comment by ta2-1** [comment] 2015-08-16 22:20
That can be related:
https://github.com/translate/pootle/blob/6d91d3bd893ffe3b768fce674cfa135dd9726d33/pootle/apps/pootle_store/models.py#L1714
we removed transaction decorator before this `update()` method. 
As I know upload uses `update()`. 
I agree that idea to trigger the async job after transaction committed is a right one. But I'd like to understand what transaction we talk about.

**Comment by phlax** [comment] 2015-08-16 22:34
In the case of the file upload ,saving the store hasnt happened when the stats refresh code is run. 

Depending on the setup (im using sqlite on my laptop) this will/not trigger - but it needs to be addressed.

django-transaction-hooks has been integrated into django 1.9 so im figuring its a pretty stable solution

**Comment by ta2-1** [comment] 2015-08-17 10:15
@phlax I don't see where 

> saving the store/units

transaction is opened. Then I suspect we are talking about transactions which Django creates automatically per every request...
I'd prefer to make `upload` in async mode as well.

**Comment by phlax** [comment] 2015-08-17 10:36
making the upload async is not a bad idea - but the problem still remains (potentially) that updates are done to the db sync and then async code is triggered against the previous state of db.

this resolves that issue.

**Comment by ta2-1** [comment] 2015-08-21 06:43
@phlax, can you confirmed that we met this problem because of `'ATOMIC_REQUESTS': True`. Will it happen if you set `'ATOMIC_REQUESTS': False`?

**Comment by phlax** [comment] 2015-08-21 07:55
@ta2-1 - no if anything it could make the problem worse

**Closed** 2015-08-21 17:10 UTC
