### ISSUE TITLE
Assign suggestions for deleted user to nobody user

### ISSUE THREAD

**Issue by unho** [translate/pootle#3811] opened 2015-06-10 14:31 UTC
It was proposed in #3651 to assign the suggestions for a given user to `nobody` before deleting that user, in order to keep the suggestions unless they are explicitly deleted.

**Comment by julen** [comment] 2015-06-11 08:49
Dupe of #3797, which is more detailed and has more info.

**Closed by julen** 2015-06-11 08:49 UTC
