### ISSUE TITLE
Copying source with \n doesn't copy the \n

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3964] opened 2015-08-11 18:39 UTC
If source text contains hardcoded `\n` and you copy source -> target then the `\n` is not copied to target.

**Comment by unho** [comment] 2015-08-11 19:02
Perhaps this is related to #3869

**Comment by julen** [comment] 2015-08-12 07:55
Can't reproduce. URL?

**Comment by julen** [comment] 2015-09-21 08:27
Closing due to lack of info. Reopen if you have specific test cases to reproduce.

**Closed by julen** 2015-09-21 08:27 UTC
