### ISSUE TITLE
Stats are broken if user accepted a suggestion that doesn't have a suggestor

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3748] opened 2015-05-18 15:04 UTC
I get the following TB when viewing [this user's](https://translations-test.documentfoundation.org/user/sophie/) [stats](https://translations-test.documentfoundation.org/user/sophie/stats/)

```pytb
Traceback (most recent call last):
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper    return bound_func(*args, **kwargs)  File "/var/www/sites/translations.documentfoundation.org/src/pootle/apps/pootle_misc/util.py", line 65, in wrapper    return f(request, *args, **kwargs)  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/var/www/sites/translations.documentfoundation.org/src/pootle/apps/evernote_reports/views.py", line 91, in dispatch
    return super(UserActivityView, self).dispatch(request, *args, **kwargs)  File "/var/www/sites/translations.documentfoundation.org/src/pootle/core/views.py", line 81, in dispatch
    .dispatch(request, *args, **kwargs)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)  File "/var/www/sites/translations.documentfoundation.org/src/pootle/apps/evernote_reports/views.py", line 94, in get
    data = get_activity_data(self.request, self.get_object(), self.month)
  File "/var/www/sites/translations.documentfoundation.org/src/pootle/apps/evernote_reports/views.py", line 412, in get_activity_data
    json['grouped'] = get_grouped_paid_words(scores, user, month)
  File "/var/www/sites/translations.documentfoundation.org/src/pootle/apps/evernote_reports/views.py", line 563, in get_grouped_paid_words
    translated_words, reviewed_words = score.get_paid_words()
  File "/var/www/sites/translations.documentfoundation.org/src/pootle/apps/pootle_statistics/models.py", line 604, in get_paid_words    }.get(self.action_code, lambda: (None, None))()
  File "/var/www/sites/translations.documentfoundation.org/src/pootle/apps/pootle_statistics/models.py", line 573, in get_sugg_reviewed_accepted
    suggester = self.submission.suggestion.user.pk
AttributeError: 'NoneType' object has no attribute 'pk'
```

**Comment by ta2-1** [comment] 2015-05-18 17:07
@dwaynebailey, do you think we should prevent such error in the code?
can you inspect why that suggestion doesn't have a suggester?
is it better to remove such suggestions and submissions, probably?

**Comment by julen** [comment] 2015-05-18 18:32
Dupe of #3651, which points to some incomplete migration.

**Closed by julen** 2015-05-18 18:32 UTC
Labels: bug
