### ISSUE TITLE
Contributor list and stat for a particular project

### ISSUE THREAD

**Issue by bellayet** [translate/pootle#4063] opened 2015-09-14 16:10 UTC
I ran a localization campaign. I need to know the top contributors and their stats in a particular project in particular locale in a date range. That will help us to recognize the contributor and motivate them by giving rewards. Is there any way to get the data?

**Comment by iafan** [comment] 2015-09-14 16:21
[This will be likely considered a duplicate of #3932]

Note that in Pootle 2.7 we introduced a notion of score — users get points proportionally to the tasks they do on the translation server, so one can query the database to sort users by score they earned during the given date range and language. We already use this information to display top contributors on the welcome page, and the underlying code allows one to specify languages as well. @julen may be able to give you the code snippet for that.

**Comment by julen** [comment] 2015-09-16 08:16
Yes, there's a way to get the data. The following snippet can get you going:

```python
from django.contrib.auth import get_user_model

User = get_user_model()

User.top_scorers(language=<language_code>, project=<project_code>, days=<NN>)
```

Arguably, `top_scorers()` should accept an arbitrary date range, instead of the last `<NN>` days.

**Closed by julen** 2015-09-16 08:16 UTC
Labels: question
