### ISSUE TITLE
Needs docs on how to configure a new project

### ISSUE THREAD

**Issue by haf** [translate/pootle#4416] opened 2016-01-22 16:21 UTC
So here I am, having followed all installation instructions, wanting to get started...

And there's no link to create a new project. A lot of [docs](http://docs.translatehouse.org/projects/pootle/en/stable-2.7.3/features/index.html) about everything else though. I google a bit, [and this is the first result](http://www.qc4blog.com/?p=88) which seems outdated, since there's now no "top menu" I can click in. [This page](http://translate.sourceforge.net/wiki/pootleadmin#creating_languages_and_projects) just says to use the "admin user" which I am, but again, no buttons...

<img width="796" alt="screen shot 2016-01-22 at 17 16 53" src="https://cloud.githubusercontent.com/assets/193115/12516111/ff9f821e-c12b-11e5-898b-a9a5011cfed3.png">

Fixing this issue would make it easier as a new-comer. Also, I think XLIFF should be the default, not PO.

**EDIT:**
Turned out there was a *red* link called "Admin" under the menu called "admin", which was my user's name. That confused me.

So a few paras on this would be great :)

**Comment by dwaynebailey** [comment] 2016-01-22 16:51
Marking this as a duplicate of #4170 

@haf yes we need some documentation on setting up projects once things are live.  We'd also realy love someone who can spend some time writing them up.  We're happy to accept pull requests with those docs.

We're looking once again at XLIFF, see pyliff project that we've started.  But the jump is quite a lot of work.  Again if you're up to assisting getting XLIFF as the basis then we'd love the help.  Even if its just testing the code that we'll be writing.

**Closed by dwaynebailey** 2016-01-22 16:51 UTC
