### ISSUE TITLE
VFolders: Stats are not refreshed after all data is recalculated 

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#3900] opened 2015-07-16 13:47 UTC
- Change any unit from a vfolder and return to browse view page. If stats is not recalculated yet you'll see this:
![image](https://cloud.githubusercontent.com/assets/682845/8724802/317b1eda-2bd9-11e5-8a6d-c087fbbf07a3.png)
- Wait until all data is recalculated. Vfolder stats won't be refreshed.
![image](https://cloud.githubusercontent.com/assets/682845/8724810/3e0f4fcc-2bd9-11e5-8dda-169526695490.png)

**Comment by unho** [comment] 2015-08-10 20:08
I am sorry, but I am unable to replicate this issue. Perhaps I am not following the same steps. This is what I did:

- Add a vfolder
- Click on the translate link on the vfolder stats table for that particular vfolder.
- Translate a unit
- Click on the "Go back to browsing" link on the editor
- Stats are displayed ok.

**Comment by ta2-1** [comment] 2015-08-11 10:08
@unho, it's important to open browse page before stats data is recalculated.
For reproducing this issue you can try to stop rqworker, translate unit, open browse page (banner should be displayed), start rqworker.

**Comment by unho** [comment] 2015-08-14 11:50
> For reproducing this issue you can try to stop rqworker, translate unit, open browse page (banner should be displayed), start rqworker.

@ta2-1 Tried several times but I don't see the banner.

**Comment by julen** [comment] 2015-08-15 11:02
I've hit this issue on the Mozilla server right now. Check out:
<img width="726" alt="dirty_stats" src="https://cloud.githubusercontent.com/assets/16768/9288571/803e3b7a-434d-11e5-8cca-cfa8eb29584c.png">

As @ta2-1 mentioned, I saw the banner of calculating stats first, then after that was done, the row for virtual folder stats wasn't updated (see that the first row is marked as dirty, but stats are calculated and there's still work TBD). If I reload the page all is fine.

**Comment by phlax** [comment] 2015-08-17 15:10
this is almost certainly #3974

**Comment by ta2-1** [comment] 2015-08-17 15:14
@phlax, I'm afraid this is not. If it is #3974 it wouldn't be updated after we refresh a page.

**Comment by julen** [comment] 2015-08-17 15:14
No, this is a pure UI issue because vfolders for some reason [return their `pk` as a key](https://github.com/translate/pootle/blob/ff9a879aafbf3c451b493b978b9a22e995aec296/pootle/apps/pootle_store/views.py#L862) in the JSON, hence updates fail because numeric IDs/class names are invalid CSS selectors.

**Comment by phlax** [comment] 2015-08-17 15:15
maybe - just that after reviewing the code I would expect errors of this nature

ie: db update triggers async code & async code uses former state of db

**Comment by julen** [comment] 2015-08-18 08:54
After further investigation, this is due to the missing *"Last Updated"* column — the vfolder contains the data, so it tries to update the column, which doesn't exist, then breaks everything else.

**Comment by unho** [comment] 2015-08-18 09:11
In the previous implementation (before adding `VFolderTreeItem`) the `get_stats` method did not return that data, so JS code just skipped it, see https://github.com/translate/pootle/commit/ee990be8b525841aa9752cc3675a410cb93a1d50#diff-2595359c0c549cb2373dc7ec23dc8cb2L180 The problem is that when `VFolderTreeItem` was added, and all the stats machinery moved to it, we blindly moved to `TreeItem.get_stats` so the data for that column is now provided. So now when JS detects the data it tries to inject it into the missing column on the DOM, and since such column is not present we get the error as reported by @julen.

**Comment by julen** [comment] 2015-08-18 09:17
I'm gonna bring back the last updated column — it's consistent with the standard browsing table and in general the width difference is non-negligible.

**Comment by unho** [comment] 2015-08-18 09:18
Looks fine to me.

**Closed** 2015-08-18 09:21 UTC
Labels: bug, ui, vfolders
