### ISSUE TITLE
Traceback on refresh_stats: KeyError: 'get_last_action'

### ISSUE THREAD

**Issue by jleclanche** [translate/pootle#3982] opened 2015-08-16 19:30 UTC
Found in my logs after a clean `refresh_stats`:

```pytb
2015-08-16T19:28:09 Set get_checks for /ta/lxmenu-data/po/ta.po
2015-08-16T19:28:09 Set get_checks for /pl/lxtask/po/pl.po
2015-08-16T19:28:09 Setting last action values for all stores...
2015-08-16T19:28:09 Set last action stats for /lg/gpicview/pootle-terminology.po
2015-08-16T19:28:09 Set last action stats for /lg/gpicview/pootle-terminology.po
2015-08-16T19:28:09 Failed to run refresh_stats
Traceback (most recent call last):
  File "/var/www/pootle/pootle.env/local/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 116, in handle_all
    self.process(**options)
  File "/var/www/pootle/pootle.env/local/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 207, in process
    self._set_last_action_stats(store_fk_filter)
  File "/var/www/pootle/pootle.env/local/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 369, in _set_last_action_stats
    del self.cache_values[key]['get_last_action']
KeyError: 'get_last_action'
```

**Comment by ta2-1** [comment] 2015-08-16 21:04
do you have any idea when this error was introduced? how to reproduce it?

**Comment by jleclanche** [comment] 2015-08-16 21:14
I don't know, but this is right after a migration from mysql to postgres with pgloader, so that might be related. I hit some other issues caused by pgloader as well, though nothing pootle can do about those.

**Comment by julen** [comment] 2015-08-17 07:36
Is */lg/gpicview/pootle-terminology.po* a real store?

**Comment by jleclanche** [comment] 2015-08-17 12:33
It's a terminology store. It definitely exists.

**Comment by julen** [comment] 2015-08-17 12:35
If *pootle-terminology.po* was created online in the past (not possible anymore), it didn't have any files associated with it.

**Comment by jleclanche** [comment] 2015-08-17 12:52
Right, sorry, it doesn't exist *on disk*.

**Comment by unho** [comment] 2015-08-18 08:23
Does syncing to disk that file solve the problem?

**Comment by jleclanche** [comment] 2015-08-18 14:25
Nope.

**Comment by phlax** [comment] 2015-08-18 14:38
Im getting this issue also - although its not exactly a clean install

It results in the job queue getting borked and eternal refresh

**Comment by phlax** [comment] 2015-08-18 14:41
after running sync_stores on the project, i now get a different error

```
2015-08-18 14:39:50,470 ERROR Failed to run refresh_stats over /zh_HK/terminology/'s files
Traceback (most recent call last):
  File "/home/phlax/.virtualenvs/pootle/pootle/pootle/apps/pootle_app/management/commands/__init__.py", line 54, in do_translation_project
    self.handle_all_stores(tp, **options)
  File "/home/phlax/.virtualenvs/pootle/pootle/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 84, in handle_all_stores
    **options)
  File "/home/phlax/.virtualenvs/pootle/pootle/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 207, in process
    self._set_last_action_stats(store_fk_filter)
  File "/home/phlax/.virtualenvs/pootle/pootle/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 366, in _set_last_action_stats
    'snippet': sub.get_submission_message()
AttributeError: 'Submission' object has no attribute 'get_submission_message'
2015-08-18 14:39:50,506 ERROR Failed to run refresh_stats over /zh_TW/terminology/'s files
Traceback (most recent call last):
  File "/home/phlax/.virtualenvs/pootle/pootle/pootle/apps/pootle_app/management/commands/__init__.py", line 54, in do_translation_project
    self.handle_all_stores(tp, **options)
  File "/home/phlax/.virtualenvs/pootle/pootle/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 84, in handle_all_stores
    **options)
  File "/home/phlax/.virtualenvs/pootle/pootle/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 207, in process
    self._set_last_action_stats(store_fk_filter)
  File "/home/phlax/.virtualenvs/pootle/pootle/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 366, in _set_last_action_stats
    'snippet': sub.get_submission_message()
```

**Comment by ta2-1** [comment] 2015-08-18 14:48
@phlax we moved pure HTML snippets from the cache (all data in stats cache should to be refreshed after this). And `refresh_stats` commands wasn't adjusted, see https://github.com/translate/pootle/issues/3835#issuecomment-129898750

**Comment by phlax** [comment] 2015-08-18 14:52
@ta2-1 yep i just raised a bug for it #3987 

I was just about to add a fix

**Comment by ta2-1** [comment] 2015-08-18 15:13
@phlax I don't know if we still need to support old `refresh_stats`. Probably it's worth to address #3548 and #3693 and drop it.

**Comment by unho** [comment] 2015-08-18 20:37
@ta2-1 Please lets drop old `refresh_stats`. I feat that it is going to confuse people, the sooner it is gone the better.

**Comment by pavels** [comment] 2015-08-29 15:20
refresh_stats_rq is the correct replacement? If sou, it would be nice to add little notice into docs ( http://pootle.readthedocs.org/en/latest/server/commands.html ) that this is the case (that refresh_stats is deprecated and refresh_stats_rq is the replacement - red warning block in refresh_stats ) - now it's confusing, what is what and what to use

**Comment by jleclanche** [comment] 2015-08-29 15:33
@pavels `refresh_stats` is what you should run. It'll be replaced by the `_rq` version once it's ready, so you won't have to change anything.

**Comment by pavels** [comment] 2015-08-29 18:09
Ok, for now only the _rq is the option because of https://github.com/translate/pootle/issues/3982#issuecomment-132235238 but i understand that these two will be swapped in the future so it is only temporary state of things.

**Comment by dwaynebailey** [comment] 2015-09-24 09:01
@pavels the docs are changed in ``2.7.2``

**Comment by dwaynebailey** [comment] 2015-09-24 09:02
We've seen major changes in this area, dropping ``refresh_stats_rq`` etc.   So closing, rather lets open a new one if we find this type of error again.

**Closed by dwaynebailey** 2015-09-24 09:02 UTC
