### ISSUE TITLE
Empty translations of empty sources show up as "Need translation"

### ISSUE THREAD

**Issue by reuben** [translate/pootle#4061] opened 2015-09-12 17:47 UTC
When the source is empty and the translation is empty the string still shows up as "Need translation" in the dashboard. Would be nice if it didn't.

**Comment by julen** [comment] 2015-09-16 08:21
Can you point us to a test case? @dwaynebailey I bet this is about mlo stats.

**Comment by reuben** [comment] 2015-09-17 13:02
Here: http://mozilla.locamotion.org/pt_BR/firefox/translate/browser/#filter=incomplete&sort=priority

**Comment by julen** [comment] 2015-09-18 07:53
I'm afraid this is by design of the underlying file formats.

On the one hand, Mozilla sometimes uses separate DTD entities to form a single sentence, and many languages have these empty because that's what makes sense to them.

On the other hand, the DTD files are converted to PO to load them up in Pootle, and this localization format doesn't have a way to translate to an empty string, as it only treats translation units as translated when they are non-empty.

What you experience is the combination of both. While source localization files need to be fixed (you should definitely report this in Firefox), it's true that Pootle is currently tied to PO when it comes to handling unit states. The latter is a known limitation reported in #1750, so I'm closing this issue in favor of that.

**Closed by julen** 2015-09-18 07:53 UTC
Labels: duplicate
