### ISSUE TITLE
Translation is not shown in the table after accepting the suggestion

### ISSUE THREAD

**Issue by iafan** [translate/pootle#4886] opened 2016-07-12 21:51 UTC
When I accept someone's suggestion and advance to a next unit, the applied translation is not shown in a previous unit.

If I then go back (Ctrl+Up) to the previous unit, I see the translation:

![a](https://cloud.githubusercontent.com/assets/1728158/16784847/a38401a8-483f-11e6-8394-d6e658fb024c.png)

---

If I press Ctrl+Down to go to the next unit, I again don't see it in the row above:

![b](https://cloud.githubusercontent.com/assets/1728158/16784877/c5c76b2e-483f-11e6-8ff1-9ce8004ea758.png)

---

Reloading the page fixes the issue. This means the submission works correctly, and the problem is with adjusting the local unit's state in the browser.

**Comment by julen** [comment] 2016-07-13 10:50
I verified that this is unrelated to core Pootle, it's caused by some of our custom code. Closing as invalid.

**Closed by julen** 2016-07-13 10:50 UTC
Labels: invalid
