### ISSUE TITLE
Wrong string count in string edit window

### ISSUE THREAD

**Issue by milupo** [translate/pootle#4821] opened 2016-06-15 13:54 UTC
Hi,
maybe it is a cosmetic bug only: Sometimes the string count in the string edit window is not correct, or, perhaps better, the count is correct but the total number of strings is not correct: The number of the current string is higher than the total number of strings. I don't know why it happens or if it causes any problem.

Here is a screenshot:

![pootle_string_count](https://cloud.githubusercontent.com/assets/1248520/16082374/55dc9bf6-3311-11e6-9924-2a3743ecdea2.png)

**Comment by phlax** [comment] 2016-06-15 14:27
hi @milupo this is a duplicate of #4640 i believe which we are just fixing.

**Closed by phlax** 2016-06-15 14:27 UTC

**Comment by milupo** [comment] 2016-06-15 14:32
Thank you, phlax.
