### ISSUE TITLE
Translation box grows while typing

### ISSUE THREAD

**Issue by SafaAlfulaij** [translate/pootle#3438] opened 2015-01-01 06:20 UTC
While typing text, The translation box grows verticaly. Pressing the Backspace key returns it to it's original state.
This is with Pootle 2.5.1 Translate Toolkit 1.11 and 2.6.0-rc2 with Translate Toolkit 1.12.0.
This issue is happening with QupZilla (QtWebKit based), It doesn't exist in Firefox or Chromium.
A video shows the problem: https://www.dropbox.com/s/nlg04q4p97gheh6/pootleTranslationBoxProblem.avi?dl=0

**Comment by jleclanche** [comment] 2015-01-01 06:24
This sounds like a qtwebkit issue to be honest. Have you tried [reporting it there](https://github.com/qupzilla/qupzilla/issues)?

**Comment by SafaAlfulaij** [comment] 2015-01-01 06:33
Qupzilla can't do anything with it, I just tried with a pure QWebView and the exact problem occurs. And if it's a Qt problem, Then nothing will be done. Qt developers will only offer security updates to QtWebKit (As someone told me on IRC).

**Comment by jleclanche** [comment] 2015-01-01 06:34
Yes, i believe qt is moving to a different web engine.

I'm closing this since it doesn't happen in gecko or blink. If you manage to reproduce it in pure webkit (safari for example), please reopen.

**Closed by jleclanche** 2015-01-01 06:34 UTC
