### ISSUE TITLE
pootle update_stores failed

### ISSUE THREAD

**Issue by liuwin7** [translate/pootle#6333] opened 2017-05-04 07:37 UTC
When I used `pootle update_stores --projects xxxx --language nl` command to update my project, the response is `CommandError: {'__all__': [u'Store with this Obsolete, Translation project and Path already exists.']}`. Then I use other options `pootle update_stores --projects xxxx --language nl --traceback -v 3`, I got these,
```pytb
Traceback (most recent call last):
  File "/home/server/pootle/env/bin/pootle", line 11, in <module>
    load_entry_point('Pootle==2.8.0rc5', 'console_scripts', 'pootle')()
  File "/home/server/pootle/env/local/lib/python2.7/site-packages/pootle/runner.py", line 317, in main
    django_settings_module='pootle.settings')
  File "/home/server/pootle/env/local/lib/python2.7/site-packages/pootle/runner.py", line 297, in run_app
    management.execute_from_command_line(command)
  File "/home/server/pootle/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/server/pootle/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/server/pootle/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/server/pootle/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/server/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/__init__.py", line 113, in handle
    raise CommandError(e)
django.core.management.base.CommandError: {'__all__': [u'Store with this Obsolete, Translation project and Path already exists.']}
```

I really don't know what I can do for this. Could you help me out?

**Comment by ta2-1** [comment] 2017-05-04 11:06
It's caused by unique index on `("obsolete", "translation_project", "tp_path")` in `Store` table.
We need to reproduce it somehow. It's worth to try following:
- get a store with a file in pootle
- remove a file
- run update_stores
- recreate the file
- run update_stores
- remove the file
- run update_stores

**Comment by liuwin7** [comment] 2017-05-04 11:15
Maybe I have removed a .po file, but i forget now. @ta2-1

**Comment by ta2-1** [comment] 2017-05-05 12:50
I couldn't reproduce it as I suggested.
@liuwin7 can you tell me if you trigger this error for any language or for `nl` only?
IIUC `nl` is used as a source language.

**Comment by ta2-1** [comment] 2017-06-14 17:54
Tested again more thoroughly with `en`, `nl` as source languages and couldn't reproduce.
I'm closing this issue however we are happy to address it if the issue still exists and you provide more info.

**Closed by ta2-1** 2017-06-14 17:54 UTC
