### ISSUE TITLE
Open sidebar doesn't push footer down

### ISSUE THREAD

**Issue by unho** [translate/pootle#3812] opened 2015-06-10 14:53 UTC
Seen in http://linode2.locamotion.org/af/firefox/

Screenshot below in case server disappears:

![screenshot](https://cloud.githubusercontent.com/assets/939880/8085567/216054e8-0f91-11e5-8bae-d219508e047e.png)

**Comment by julen** [comment] 2015-06-11 08:19
I cannot reproduce this neither locally nor in the link you provided nor in [our production server](https://translate.evernote.com/zh_CN/web_evernote/) (Firefox, Chromium, Safari).

**Comment by julen** [comment] 2015-06-11 08:20
You probably had improperly built assets and this has been a transient issue? Would be great to confirm.

**Comment by unho** [comment] 2015-06-11 08:30
I can confirm that I refreshed the server several times to force retrieval of last version from server. I also asked @dwaynebailey to rebuild assets and the problem persists.

**Comment by julen** [comment] 2015-06-11 08:43
Last (and supported) version is 43.

**Comment by unho** [comment] 2015-06-11 09:29
Just updated to Chromium 43 and the problem persists after several force refreshes and wiping all cache.

**Comment by dwaynebailey** [comment] 2015-06-19 09:01
Testing on mlo migration this seems to happen as follows:

1. Not a problem when the list of items in the browser is less than the size of the browser screen.  In this case the footer appears correctly at the bottom of the sidebase
2. A problem when the list of items in the browser occupies more than one browser screen, i.e. you need to scroll down to see further files and directories.  In this case the footer will appear directly below the last item in the browser and cut across the sidebar.

**Comment by julen** [comment] 2015-06-19 13:17
FWIW I can only see this on mlo – do you guys have any customizations on the server? The code that fixes the sidebar height doesn't kick in.

**Comment by dwaynebailey** [comment] 2015-06-20 09:13
@julen @unho got it.

This only occurs in this instance:

1. We have a project announcements, and
2. We have a language announcement.

When we have that we get the stripe through the middle.

**Comment by phlax** [comment] 2015-08-11 15:58
im working on this...

**Comment by phlax** [comment] 2015-08-11 17:10
this appears to have been fixed in commit 6a0d4d6

however it does not calculate the sidebar height correctly - so the footer is pushed much further down than it should be...

**Closed** 2015-08-13 17:10 UTC
Labels: ui
