### ISSUE TITLE
Migration fails on clean install

### ISSUE THREAD

**Issue by Frexuz** [translate/pootle#6152] opened 2017-03-19 10:46 UTC
```
pootle migrate
System check identified some issues:

WARNINGS:
?: (pootle.W004) Email server is not available.
	HINT: Review your email settings and make sure your email server is working.
?: (pootle.W006) The sqlite database backend is unsupported
	HINT: Set your default database engine to postgresql or mysql
?: (pootle.W010) DEFAULT_FROM_EMAIL is using the following default setting 'info@YOUR_DOMAIN.com'.
	HINT: DEFAULT_FROM_EMAIL is used in all outgoing Pootle email.
Don't forget to review your mail server settings.
?: (pootle.W011) POOTLE_CONTACT_EMAIL is using the following default setting 'info@YOUR_DOMAIN.com'.
	HINT: POOTLE_CONTACT_EMAIL is the address that will receive messages sent by the contact form.
Operations to perform:
  Apply all migrations: account, accounts, auth, contenttypes, pootle_app, pootle_comment, pootle_config, pootle_data, pootle_format, pootle_fs, pootle_language, pootle_project, pootle_revision, pootle_score, pootle_statistics, pootle_store, pootle_translationproject, pootle_word, reports, sessions, sites, socialaccount, staticpages, virtualfolder
Running migrations:
  Applying accounts.0001_initial... OK
  Applying account.0001_initial... OK
  Applying account.0002_email_max_length... OK
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying pootle_app.0001_initial... OK
  Applying pootle_language.0001_initial... OK
  Applying accounts.0002_user_alt_src_langs... OK
  Applying accounts.0003_remove_pootleprofile_id... OK
  Applying accounts.0004_allow_null_last_login... OK
  Applying accounts.0005_user_indeces... OK
  Applying accounts.0006_unicode_usernames_are_valid... OK
  Applying accounts.0007_update_system_username... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying pootle_project.0001_initial... OK
  Applying pootle_translationproject.0001_initial... OK
  Applying pootle_store.0001_initial... OK
  Applying pootle_translationproject.0002_remove_translationproject_disabled... OK
  Applying pootle_translationproject.0003_realpath_can_be_none... OK
  Applying pootle_translationproject.0004_add_reverse_tp_idx... OK
  Applying pootle_store.0002_make_suggestion_user_not_null... OK
  Applying pootle_store.0003_remove_unit_ordering... OK
  Applying pootle_store.0004_index_store_index_together... OK
  Applying pootle_store.0005_unit_priority... OK
  Applying pootle_store.0006_remove_auto_now_add... OK
  Applying pootle_store.0007_case_sensitive_schema... OK
  Applying pootle_store.0008_flush_django_cache...Flushing cache...
All default Django cache data removed.
 OK
  Applying pootle_format.0001_initial... OK
  Applying pootle_format.0002_default_formats... OK
  Applying pootle_store.0009_store_filetype... OK
  Applying pootle_project.0002_remove_dynamic_model_choices_localfiletype... OK
  Applying pootle_project.0003_case_sensitive_schema... OK
  Applying pootle_project.0004_correct_checkerstyle_options_order... OK
  Applying pootle_project.0005_add_none_treestyle... OK
  Applying pootle_project.0006_project_filetypes... OK
  Applying pootle_project.0007_migrate_localfiletype... OK
  Applying pootle_store.0010_set_store_filetypes... OK
  Applying pootle_store.0011_store_is_template... OK
  Applying pootle_store.0012_set_is_template... OK
  Applying pootle_store.0013_set_store_filetype_again... OK
  Applying pootle_store.0014_add_unit_index_togethers... OK
  Applying pootle_store.0015_add_slashes_validator_for_name... OK
  Applying pootle_store.0016_blank_last_sync_revision... OK
  Applying pootle_statistics.0001_initial... OK
  Applying pootle_statistics.0002_update_submission_ordering... OK
  Applying pootle_statistics.0003_scorelog_translated_wordcount... OK
  Applying pootle_statistics.0004_fill_translated_wordcount... OK
  Applying pootle_data.0001_initial... OK
  Applying pootle_data.0002_storechecksdata_tpchecksdata... OK
  Applying pootle_data.0003_index_unique_together... OK
  Applying pootle_data.0004_remove_last_updated... OK
  Applying pootle_data.0005_add_store_and_tp_data... OK
  Applying pootle_data.0006_add_cascade_deletes... OK
  Applying pootle_app.0002_mark_empty_dirs_as_obsolete... OK
  Applying pootle_app.0003_drop_existing_directory_default_permissions... OK
  Applying pootle_app.0004_set_directory_has_no_default_permissions... OK
  Applying pootle_app.0005_case_sensitive_schema... OK
  Applying pootle_app.0006_change_administrate_permission_name... OK
  Applying pootle_app.0007_add_directory_name_validation... OK
  Applying pootle_app.0008_allow_blank_directory_name_and_parent... OK
  Applying pootle_app.0009_set_default_directory_pootle_path... OK
  Applying pootle_app.0010_obsolete_path_idx... OK
  Applying pootle_app.0011_directory_tp... OK
  Applying pootle_app.0012_set_directory_tp... OK
  Applying pootle_app.0013_directory_tp_path... OK
  Applying pootle_app.0014_set_directory_tp_path... OK
  Applying pootle_app.0015_add_tp_path_idx... OK
  Applying pootle_translationproject.0005_remove_empty_translationprojects... OK
  Applying pootle_language.0002_case_insensitive_schema... OK
  Applying pootle_app.0016_set_directory_tp_again... OK
  Applying pootle_app.0017_drop_stray_directories... OK
  Applying pootle_app.0018_set_directory_base_manager_name... OK
  Applying sites.0001_initial... OK
  Applying pootle_comment.0001_initial... OK
  Applying pootle_comment.0002_use_abstract_module... OK
  Applying pootle_config.0001_initial... OK
  Applying pootle_data.0007_add_store_and_tp_data_again... OK
  Applying pootle_fs.0001_initial... OK
  Applying pootle_language.0003_ensure_unique_special_chars... OK
  Applying pootle_project.0008_remove_project_localfiletype... OK
  Applying pootle_project.0009_set_code_as_fullname_when_no_fullname... OK
  Applying pootle_project.0010_add_reserved_code_validator... OK
  Applying pootle_project.0011_add_project_checker_validator... OK
  Applying pootle_project.0012_set_pootle_fs_treestyle... OK
  Applying pootle_project.0013_rename_treestyle_choice_to_pootle_fs... OK
  Applying pootle_project.0014_just_rename_label_for_choice... OK
  Applying pootle_project.0015_rename_fs_treestyle... OK
  Applying pootle_revision.0001_initial... OK
  Applying pootle_statistics.0005_index_ordering... OK
  Applying pootle_translationproject.0006_relink_or_drop_orphan_translationprojects... OK
  Applying pootle_score.0001_initial... OK
  Applying pootle_score.0002_set_user_scores... OK
  Applying pootle_statistics.0006_set_submission_base_manager_name... OK
  Applying pootle_statistics.0007_submission_revision... OK
  Applying pootle_statistics.0008_set_submission_revisions... OK
  Applying virtualfolder.0001_initial... OK
  Applying virtualfolder.0002_set_unit_priorities... OK
  Applying virtualfolder.0003_case_sensitive_schema... OK
  Applying pootle_store.0017_store_priority... OK
  Applying pootle_store.0018_move_priority_to_store... OK
  Applying pootle_store.0019_remove_unit_priority... OK
  Applying pootle_store.0020_store_tp_path... OK
  Applying pootle_store.0021_set_tp_path... OK
  Applying pootle_store.0022_add_unique_tp_path_idx... OK
  Applying pootle_store.0023_add_unit_store_idxs... OK
  Applying pootle_store.0024_set_store_base_manager_name... OK
  Applying pootle_translationproject.0007_set_tp_base_manager_name... OK
  Applying pootle_word.0001_initial... OK
  Applying pootle_word.0002_set_cs_schema... OK
  Applying pootle_word.0003_add_word_stems...Traceback (most recent call last):
  File "/home/frexuz/pootle/env/bin/pootle", line 11, in <module>
    sys.exit(main())
  File "/home/frexuz/pootle/env/local/lib/python2.7/site-packages/pootle/runner.py", line 317, in main
    django_settings_module='pootle.settings')
  File "/home/frexuz/pootle/env/local/lib/python2.7/site-packages/pootle/runner.py", line 297, in run_app
    management.execute_from_command_line(command)
  File "/home/frexuz/pootle/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/frexuz/pootle/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/frexuz/pootle/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/frexuz/pootle/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/frexuz/pootle/env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/frexuz/pootle/env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/frexuz/pootle/env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/frexuz/pootle/env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/frexuz/pootle/env/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/frexuz/pootle/env/local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 189, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/frexuz/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_word/migrations/0003_add_word_stems.py", line 23, in stem_terminology_words
    site_stopwords = stopwords.get().words
  File "/home/frexuz/pootle/env/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/frexuz/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_word/utils.py", line 31, in words
    with open(fpath) as f:
IOError: [Errno 2] No such file or directory: '/home/frexuz/pootle/env/local/lib/python2.7/site-packages/translate/../share/stoplist-en'
```

I just followed the install documentation.

Ubuntu 16.04
Python 2.7.12
pip 9.0.1
Pootle 2.8.0rc5 (Django 1.10.6, Translate Toolkit 2.0.0)

redis and rqworkers are running

Ideas?

**Comment by phlax** [comment] 2017-03-19 10:55
hi @Frexuz not sure off hand - altho we had to mangle the stoplist path for different environments - trying to think why its not there in your env

**Comment by phlax** [comment] 2017-03-19 10:56
actually - looking at the path its creating it seems wrong - so i suppose the question is more as to why its trying to create that path - ill look into it

**Comment by Frexuz** [comment] 2017-03-30 08:39
Any progress? :)

**Comment by phlax** [comment] 2017-03-30 08:47
hi @Frexuz if you can jump on our gitter channel - i can try and work out why it fails https://gitter.im/translate/pootle

**Comment by phlax** [comment] 2017-03-30 10:15
after upgrading the missing directory was there

i tried to reproduce the ttk install with missing directory without success - closing this as anomalous - we can reopen if it recurs

**Closed by phlax** 2017-03-30 10:15 UTC

**Comment by phlax** [comment] 2017-07-24 11:08
the resolution to this problem (not sure how its created) is i think to force re-download of the package

```
pip uninstall translate-toolkit
pip install --no-cache-dir translate-toolkit
```

**Comment by Johennes** [comment] 2017-09-18 11:25
I'm consistently running into this on macOS. Running

```
pip uninstall translate-toolkit
pip install --no-cache-dir translate-toolkit
```

*before* running `pootle migrate` fixes it.

**Comment by vinyldarkscratch** [comment] 2018-12-18 02:02
The above solution worked perfectly over here.  Digging into the problem a little bit, it seems to be due to the fact that Pootle wants an older version of translate-toolkit, as suggested by the following line:
`pootle 2.8.2 has requirement translate-toolkit==2.2.5, but you'll have translate-toolkit 2.3.1 which is incompatible.`

Doing a little bit of testing, I can confirm that this is indeed the issue.  Reinstalling translate-toolkit without the `--no-cache-dir` argument also produces no error.
