### ISSUE TITLE
Make resources list query work in all DB backends

### ISSUE THREAD

**Issue by julen** [translate/pootle#3570] opened 2015-02-02 14:03 UTC
The current resources list which is used in the last drop-down only works for MySQL backends, since it uses a custom SQL query with some MySQL-only functions. The query needs to be adapted to whichever DB backends master wants to support.

**Comment by dwaynebailey** [comment] 2015-02-02 14:20
Duplicate of #3539

**Closed by dwaynebailey** 2015-02-02 14:20 UTC
Labels: bug
