### ISSUE TITLE
RemovedInDjango110Warning: SubfieldBase has been deprecated

### ISSUE THREAD

**Issue by unho** [translate/pootle#5448] opened 2016-10-25 19:01 UTC
I am seeing this warning everywhere. Not a problem but quite annoying:

```
WARNING /var/www/sites/mozilla/src/pootle/apps/pootle_store/fields.py:51: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  class MultiStringField(models.Field):
```

**Comment by julen** [comment] 2016-10-26 11:33
Closing as a duplicate of #5268.

**Closed by julen** 2016-10-26 11:33 UTC
