### ISSUE TITLE
Quality checks and fuzzy units

### ISSUE THREAD

**Issue by khaledhosny** [translate/pootle#3879] opened 2015-07-04 16:24 UTC
Quality checks should be skipped for fuzzy units, since these units can contain anything, for example automatically suggested translations that might have placeholder not present in the source string which will cause them to be marked as critical errors needlessly (which is more annoying now because they are visible than before).

**Comment by iafan** [comment] 2015-07-05 22:23
Fuzzy units are synchronized with .po files, and may end up being used just as regular translations, and breaking builds if there are errors with e.g. placeholders. Thus, I'd prefer to keep displaying critical errors for such units. In the end, translators may want to review all critical checks first (to make sure builds don't break), then deal with the rest not-so-critical units that need work.

So count me as +1 on closing this issue.

**Comment by khagaroth** [comment] 2015-07-07 12:51
If fuzzy strings break build, then there is something terribly wrong with the build configuration. I agree with khaled, fuzzy strings should be ignored.

**Comment by dwaynebailey** [comment] 2015-08-24 08:59
OK so I'm hearing two conerns here:

1. Critical checks exposed in fuzzy are exposing these when they are in fact not critical @khagaroth and @khaledhosny's view
2. Fuzzy may be used @iafan and thus we should clean these also.  A kind of every string should be clean of critical check errors if it is in Pootle view.

My view is though I want to see 2) in that a fuzzy string may be resurected in which case you'd prefer it to be clean.  I don't agree with @iafan that fuzzy units could be used, they could of course, but they really really shouldn't without knowing that they could be broken.  I know on Mozilla servers we have people faced by a large number of issues, many false positives simply because they are in fuzzy strings.

My leaning is that we shouldn't display critical errors if the unit is fuzzy.  If its fuzzy really the first requirement is that the unit be translated.

@iafan care to give your input again here?

**Comment by khaledhosny** [comment] 2015-08-24 09:33
May a middle ground would to only show the errors when editing the fuzzy unit but without adding them to the overall errors so that one can effectively ignore them until it really matters.

**Comment by unho** [comment] 2015-08-24 09:33
My personal opinion is that we should only enforce quality checks on actual final translations.

Nobody cares if suggestions, or fuzzy translations, or TM results are completely broken because to make to a final translation they must be accepted/unfuzzied/copied by a human translator which then will have to address the failing quality checks in order to submit the final translation.

I agree that @iafan view that everything on Pootle should be in perfect shape would be good, but that feels like an ideal scenario.

**Comment by unho** [comment] 2015-08-24 09:34
> May a middle ground would to only show the errors when editing the fuzzy unit but without adding them to the overall errors so that one can effectively ignore them until it really matters.

+1

**Comment by iafan** [comment] 2015-08-24 17:41
Let me recap my understanding where this problem comes from:

1. In some setups (e.g. in default gettext flow, where .po are compiled into .mo) fuzzy strings are not included in the final resource file
2. In some setups, fuzzy strings can somehow contain real incorrect (broken) translations.
3. In some setups, there are many checks that give false positives, and some non-critical checks are exposed as critical.

Given those assumptions, I can easily see people being frustrated with the number of checks they see, and the natural temptation is to at least not display the checks which belong to fuzzy strings — which would help one to deal with the critical errors is non-fuzzy strings first.

My strong feeling here is that approach is simply masking problems with such setups. Before I explain my reasoning below, I'd like to describe what I think the proper workflow is:

1. Fuzzy flag should be used in two situations:
  - when translator provides a translation, but wants to have it revised later. Even if the translator marks the translation as needing work, everybody would benefit from checking the translation against errors. Moreover, I do hope that someday we can implement live as-you-type checking of the translation, no matter if it is marked as fuzzy or not,
  - when translation is provided by some robot (comes from update_stores from a .po file). In such a case, I would expect such translation only be populated if they don't contain any garbage. 

2. There's a reason why some checks are called critical. If some checks are not-critical, they need to be marked as such. In a normal translation workflow, the number of critical checks needs to be brought down to zero as soon as possible.

3. In Pootle, we have a 'similar translations' feature — this is where all fuzzy translations should better come from. When people are translating stuff, they can choose the similar translation and fix it right away.

My intention is to provide an UI that will help user not to introduce any new errors as they translate, and help users identify and fix the critical errors right away. Disregarding the semantics of the fuzzy flag (whether it is used in the final resource files or not), it is in our best interest to indicate the error as early as we can, to help educate the translator and to minimize the chance the error is propagated into the resource files.

> I agree that @iafan view that everything on Pootle should be in perfect shape would be good, but that feels like an ideal scenario.

That is a pretty achievable scenario, and it already works for Evernote. We keep critical errors at zero level, and this is partly because we indicate such errors as early as we can.

> Nobody cares if suggestions, or fuzzy translations, or TM results are completely broken because to make to a final translation they must be accepted/unfuzzied/copied by a human translator which then will have to address the failing quality checks in order to submit the final translation.

Not exactly. Suggestions or TM results never leave translation server and are used as pure translation aids. But when it comes to fuzzy translations, they are exported to the final resource file. So they can potentially be used in translations. I don't say it's good or bad. It's pure semantics. One may feel that "fuzzy strings should not be used as they are not totally production-ready". The other may treat them as "these translations can are already be used, and just need someone's review". In Evernote, we use latter, and it perfectly works for us.

> I don't agree with @iafan that fuzzy units could be used, they could of course, but they really really shouldn't without knowing that they could be broken.

This is exactly my point: if the fuzzy units are used in some setup (and there's nothing wrong with that), people really should know if there are any problems with them.

I think the core of the problem is:
1. pre-populating .po files with incorrect translations, which abuses the checks functionality and distracts users. Similar translations and suggestions should better be used for that purpose.
2. having too many false positive checks (and having some non-critical checks falling into the 'critical' category).

I would prefer people to really think about addressing these two (or at the very least the second one) before trying to mute what I feel is an extremely important feedback in the UI.

If you are still inclined to have no checks displayed for the fuzzy units, and since the semantics of using the fuzzy flag can obviously be different, the only solution I find viable is to provide some global config flag (`POOTLE_SKIP_FUZZY_UNIT_CHECKS`) that would affect the stats generation logic.

**Comment by unho** [comment] 2015-08-24 18:03
> If you are still inclined to have no checks displayed for the fuzzy units, and since the semantics of using the fuzzy flag can obviously be different, the only solution I find viable is to provide some global config flag (POOTLE_SKIP_FUZZY_UNIT_CHECKS) that would affect the stats generation logic.

In the middle ground scenario failing checks for fuzzy units are still displayed on the editor, but not in the browser view, so stats generation logic must not be affected in any way.

**Comment by unho** [comment] 2015-08-24 18:04
Damn! Hit the wrong button. Sorry!

**Comment by dwaynebailey** [comment] 2015-08-25 08:09
> I think the core of the problem is:
> 1. pre-populating .po files with incorrect translations, which abuses the checks functionality and distracts users. Similar translations and suggestions should better be used for that purpose.
> 2. having too many false positive checks (and having some non-critical checks falling into the 'critical' category).

1. Yip in mlo that is the source of many of these.  They're fuzzy matches, so its debatiable if they are incorrect translations.  But yes now that Pootle is on 2.7.0, the TM suggestions provide a better live approach to this kind of fuzzy matching.  We already have fuzzy matching off so we shouldn't see more of these except where Gettext itself is making these.  But the reality is that Pootle should be able to pull in a PO file that might have been fuzzy populated in any number of ways and just do the right thing with it.

2. No that's not the issue.  The critical checks are almost all positive matches and these are exposed in the Browse view.  And no there are no non-critical checks in the critical category.  The changes introduced in #3988 address the issue if knowing which checks are critical in the editor (which might go some way to address this whole issue)
 
> I would prefer people to really think about addressing these two (or at the very least the second one) before trying to mute what I feel is an extremely important feedback in the UI.

I don't think that hits the core issue to be honest.  For a mlo user the issue is that the check is critical but it's in a unit that will not be used.  So it's forcing a translator to prioritise translating something that might not actually be a priority compared to other things.

> If you are still inclined to have no checks displayed for the fuzzy units, and since the semantics of using the fuzzy flag can obviously be different, the only solution I find viable is to provide some global config flag (POOTLE_SKIP_FUZZY_UNIT_CHECKS) that would affect the stats generation logic.

I'd like to avoid this like the plague.  But its likely the correct solution in the interim.

I think the crux of the matter is this comment:

> The other may treat them as "these translations can are already be used, and just need someone's review". In Evernote, we use latter, and it perfectly works for us.

In other words Evernote needs the checks on in fuzzy units because you actually will use them.  Others need them off because they follow Gettext PO semantics in that Gettext will not use a fuzzy unit.

Which means we have two competing views of what a fuzzy unit is in Pootle.

And I think the summary of that is that we're not thinking in terms of Pootle but in terms of PO files. Where we should be dealing with this when files are serialised out and have a consistent non-format specific UI experience.

So my proposal to go forward is this:

1. The real way to address this is the model redesign and breaking away from PO centric view of the world. That is Pootle is a translation tool and we deal with format specifics and adapations for a specific project when we serialise things.  But this will take some time to implemen...so.
2. For now we follow PO and don't bother with checks in fuzzy units because by default these are not used.  Thus we use the setting proposed by @iafan which is set on by default.  With the aim of getting rid of this when we address 1 above.
3. We deal with any checks issues as we see them.

**Comment by iafan** [comment] 2015-08-25 16:47
> But yes now that Pootle is on 2.7.0, the TM suggestions provide a better live approach to this kind of fuzzy matching. We already have fuzzy matching off so we shouldn't see more of these except where Gettext itself is making these.

Since you seem to agree that TM suggestions are better for fuzzy matching, and since you have disabled populating fuzzy matches with unverified stuff, then it opens another possibility of fixing this for MLO:

How about creating a small script that will go through all fuzzy units that have critical errors, and remove these fuzzy submissions? I guess the TM is already populated with all existing translations, so MLO won't lose anything with this cleanup, and this reduce the number of critical checks for them, helping focus on the ones that really matter. I bet this is a pretty easy thing  to do — probably even easier than implementing this config setting.

**Comment by iafan** [comment] 2015-08-25 17:08
Side comment on our workflow: sometimes we raise "Needs work" flag on already existing translations. This happens in two cases:
1. we get some complaint or notice something inconsistent in the translation, and want translators to verify the string again.
2. we upload a screenshot to the unit, and this automatically raises the "Needs Work" flag for translators to validate the translation based in the new context information.

In both such cases, we definitely don't want the string to be reverted to the English variant in localized resources for the time it is being reviewed (this is what would have happened if we had the default "fuzzy strings should not be used" flow). In our case, string never disappears from the localized resources, and we get a very nice and seamless verification workflow. At the same time, we always have an ability to clear the translation if we absolutely need to.

I believe that actually every localization setup would benefit from this approach, now that we have lighting fast TM and don't need to pre-populate translations with garbage.

**Closed** 2019-02-02 22:37 UTC
Labels: editor, mlo, ui
