### ISSUE TITLE
Incorrect application of the printf() check

### ISSUE THREAD

**Issue by tasso85** [translate/pootle#3560] opened 2015-01-29 11:51 UTC
I have noticed this issue when translating a project for which the template language is Italian and I am doing a plural translation in another language.

For example if I have, in the template

SINGULAR: Successivo
PLURAL: %1$d Successivi

which then is translated in English as

SINGULAR: Next
PLURAL: Next %1$d

Pootle will say that this fails the printf() check, however it looks fine to me.

Is this intended behaviour, or is it actually wrong?

**Comment by dwaynebailey** [comment] 2015-01-29 12:09
@tasso85 this is the intended behaviour for the following reasons:

1. We don't do any specific checks on the format to know what coding language and this variable handling is being used.  For some languages this means that you cannot drop a variable in a plural form, it must always be present.
2. The Gettext approach is that a variable is always present in plural forms.
3. The example strings don't actually look like the correct application of plural form handling, they just happen to work for some European languages.  The first form in some languages does not necessarily mean 1 and might be reused in for example 21, 31, etc..  In my mind it makes sense to separate those and actually handle 'Next %d' on its own as a plural.

**Comment by tasso85** [comment] 2015-01-29 13:12
I'm not sure I get all your talk about different plural forms, I can assure you that we are correctly managing it, even if for the time being our app happen to be localized only in languages with two plural forms.

However, it'd seem more natural to me to compare singular with singular and plurals with plurals, wouldn't it?

**Comment by dwaynebailey** [comment] 2015-01-29 16:15
@tasso85 first lets deal with printf side of things.  There are many languages that do not have two forms e.g. Arabic with 6.  So which do we compare with which? We take the safest root and make sure the variable occurs correctly in all units, mostly because it should.

Next back to your plural form.  Have a look at the Belarusian entry in the [CLDR plural forms](http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html).

Now your string works like this assuming singular is 1:

0 Next 0
1 Next 1
2 Next 2
...
21 Next
22 Next 22

It simply cannot be assumed that the first form of a plural is 1, and it cannot be assumed that the first form won't be reused again for another number.  If you need the translation for Next 1 then just make it its own unit and deal with Next %d correctly as a single plural item.

**Comment by dwaynebailey** [comment] 2015-08-11 13:46
I'm closing this now, its the inteded behaviour that we have now.

**Closed by dwaynebailey** 2015-08-11 13:46 UTC
