### ISSUE TITLE
Upgrade failed: django.db.utils.OperationalError: (1091, "Can't DROP 'description_html'; check that column/key exists")

### ISSUE THREAD

**Issue by princeofnaxos** [translate/pootle#3953] opened 2015-08-09 07:26 UTC
Upgrading from v2.5.1 to 2.6.0, `pootle setup` fails with this error message;

`django.db.utils.OperationalError: (1091, "Can't DROP 'description_html'; check that column/key exists")`

I checked the database for that field, but it isn't there.

How do I proceed?

**Comment by princeofnaxos** [comment] 2015-08-09 07:37
Solved this one by adding the field to pootle_app_project instead of pootle_app_translationproject, as stated in the text of the error message.
But now setup encounters even more missing fields....

**Comment by jleclanche** [comment] 2015-08-09 07:38
What's 2.5.1?

**Comment by princeofnaxos** [comment] 2015-08-09 07:40
Wasn't 2.5.1 the last version before 2.6.0? I might be mistaken there...

**Comment by princeofnaxos** [comment] 2015-08-09 07:44
Sorry to confuse you..... I'm upgrading from 2.5.1.

**Comment by jleclanche** [comment] 2015-08-09 08:07
Ok, thank you. I'll look into this tomorrow.

**Comment by princeofnaxos** [comment] 2015-08-12 12:26
Tomorrow is 2 days ago... Any clue to what is causing this issue?

**Comment by phlax** [comment] 2015-09-07 09:49
@princeofnaxos apologies it has taken some time to address this issue. We are currently working on a 2.7.1 release to address bugs and migration issues in the 2.7.0 release.

I believe this may be fixed in #4037 - would you be willing to test this for us?

**Comment by phlax** [comment] 2015-09-10 08:51
@princeofnaxos im going to close this ticket as i believe the problem will be resolved in the 2.6.1 release - which we will be releasing in the next few days.

If the problem persists please re-open ticket and we can investigate further.

**Comment by dwaynebailey** [comment] 2016-01-09 09:09
Reopening as @princeofnaxos reported this still present on the mailing list.  From the traceback it seems it's a 2.6.2 release

```pytb
Traceback (most recent call last):
   File "/var/www/pootle/env/bin/pootle", line 9, in <module>
     load_entry_point('Pootle==2.6.2', 'console_scripts', 'pootle')()
   File
"/var/www/pootle/env/local/lib/python2.7/site-packages/pootle/runner.py", line
171, in main
     django_settings_module='pootle.settings')
```

**Comment by dwaynebailey** [comment] 2016-01-09 09:09
@princeofnaxos I think to make this fix really quick it would be great if you could share your DB with one of the devs.

**Comment by phlax** [comment] 2016-01-15 11:29
@princeofnaxos ive tested out your db and it seems that the migrations have some problems prior to the 2.5 to 2.6 upgrade.

Not sure how its happened, but i can probably help to get through the migration.

ping me on IRC (freenode#pootle) or on gitter.im/translate/pootle and ill try and help

**Comment by phlax** [comment] 2016-02-10 12:23
hi @princeofnaxos afaict this issue is specific to your db - ping me on gitter if you want to follow up, or reopen if you think the problem is wider and ill happily follow up.

**Closed by phlax** 2016-02-10 12:23 UTC
Labels: db/migrations
