### ISSUE TITLE
Some shortcuts does not work on Mac OS X

### ISSUE THREAD

**Issue by khaledhosny** [translate/pootle#3871] opened 2015-06-27 12:08 UTC
I’m testing on Mac OS X (using Firefox) and the following shortcuts does not work:

`Ctrl+Shift+.`
`Ctrl+Shift+End`
`Ctrl+Shift+,`
`Ctrl+Shift+Home`

Furthermore, I think it is more intuitive on Mac to use `Command` and `Option` keys instead of `Ctrl` and `Shift` (but I’m not a regular Mac user, so this might be wrong).

**Comment by dwaynebailey** [comment] 2015-06-27 15:34
@khaledhosny have you tried to see if those work using alternative key combinations?  The shortcut code is pretty easy to find in the JS. Not sure if it adapts to Mac

**Comment by khaledhosny** [comment] 2015-06-27 23:19
Checking the [source](https://github.com/translate/pootle/blob/master/pootle/static/js/editor/app.js) I see only ctrl+shift+space and ctrl+shift+n and they do in fact work, so I think the tooltip on the navigation arrow is wrong or those shortcuts went missing during the source code restructuring.

**Comment by dwaynebailey** [comment] 2015-06-28 15:43
@khaledhosny would you be able to make a patch and pull request for this?

**Comment by khaledhosny** [comment] 2015-06-28 15:59
Not sure what should be the fix here, remove the tool tips or restore the shortcuts?

**Comment by dwaynebailey** [comment] 2015-07-04 17:19
@khaledhosny I'd try restore the shortcut if it makes sense or is easy.  Otherwise simply remove the tooltip

**Comment by julen** [comment] 2015-07-05 08:29
+1 on using *native* modifiers for shortcuts, in Mac these being Cmd and Option. The issue is the underlying library we use is pretty old and didn't support Cmd/Option last time I checked.

**Comment by khaledhosny** [comment] 2015-07-05 15:00
So it seems that https://craig.is/killing/mice allows to bind multiple shortcuts to the same function, so we can use regular and Mac-specific shortcuts at the same time. Is it OK to switch to this?

**Comment by khaledhosny** [comment] 2015-07-05 15:03
Hmm, it can even be made to use Ctrl or Command based on the OS.

**Comment by iafan** [comment] 2015-08-13 23:23
I'll close this issue in favor of https://github.com/translate/pootle/issues/3136

**Closed by iafan** 2015-08-13 23:23 UTC
Labels: bug
